name: afib
version: 0.0.10
description: >-
  Beta framework for flutter.
homepage: https://afibframework.org
documentation: https://afibframework.org/docs
environment:
  sdk: ">=2.15.0 <3.12.0"
publish_to: none

dependencies:
  flutter:
    sdk: flutter
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  intl: ^0.18.1
  colorize: ^3.0.0
  logger: ^1.1.0  
  package_info_plus: ^4.0.1
  quiver: ^3.0.1
  path: ^1.8.0
  overlay_support: ^2.0.1
  stack_trace: ^1.10.0
  pubspec_parse: ^1.2.0
  args: ^2.3.0
  plural_noun: ^0.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

executables:
  afib_bootstrap: