name: afib
version: 0.0.10
description: >-
  Beta framework for flutter.
homepage: https://afibframework.org
documentation: https://afibframework.org/docs
environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  redux: ^4.0.0
  flutter_redux: ^0.6.0
  intl: ^0.16.1
  colorize: ^2.0.0
  logger: ^0.9.2  
  package_info: ^0.4.3
  quiver: ^2.1.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  stack_trace: ^1.9.3    
  effective_dart: ^1.2.0  
  
executables:
  afib: