name: afib
version: 0.0.10
description: >-
  Beta framework for flutter.
homepage: https://afibframework.org
documentation: https://afibframework.org/docs
environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  redux: ^4.0.0
  flutter_redux: ^0.6.0
  redux_logging: ^0.4.0
  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  stack_trace: ^1.9.3    


executables:
  afib: