name: afib
version: 0.0.10
description: >-
  Beta framework for flutter.
homepage: https://afibframework.org
documentation: https://afibframework.org/docs
environment:
  sdk: ">=2.9.0 <3.0.0"
publish_to: none

dependencies:
  flutter:
    sdk: flutter
  redux: ^5.0.0
  flutter_redux: ^0.8.2
  intl: ^0.17.0
  colorize: ^3.0.0
  logger: ^1.0.0  
  package_info_plus: ^1.0.1
  quiver: ^3.0.1
  path: ^1.8.0
  overlay_support: ^1.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  stack_trace: ^1.9.5    
  effective_dart: ^1.2.0  
  args: ^1.6.0
  
executables:
  afib_bootstrap: