name: afib
version: 0.5.3
description: >-
  Beta framework for flutter.
homepage: https://www.afibframework.io
documentation: https://docs.afibframework.io/v0.5/afib/startup/start_here/
repository: https://github.com/chrisjones314/afib
issue_tracker: https://github.com/chrisjones314/afib/issues
environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  intl: ^0.20.1
  colorize: ^3.0.0
  logger: ^2.0.1  
  package_info_plus: ^4.1.0
  quiver: ^3.2.1
  path: ^1.8.3
  overlay_support: ^2.1.0
  stack_trace: ^1.11.0
  pubspec_parse: ^1.2.3
  args: ^2.4.2
  plural_noun: ^0.1.2
  meta: ^1.9.1
  collection: ^1.17.1
  material_color_utilities: ^0.11.1
  flutter_test:
    sdk: flutter
  
dev_dependencies:
  flutter_lints: ^2.0.2

executables:
  afib_bootstrap: