name: afib-smoketest-action
run-name: Run AFib Smoketest
on: 
  push:
    branches:
      - master
jobs:
  setup:
    runs-on: macos-latest
    steps:
      - name: Checkout afib
        uses: actions/checkout@v3
        with: 
          ref: master
      - name: Inspect filesystem
        run: ls ~/
      - name: Inspect current directory
        run: pwd
      - name: Inspect filesystem 2
        run: ls
